### ISSUE TITLE
Unstable tests in ubuntu xenial

### ISSUE THREAD

**Issue by Sulverus** [tarantool/avro-schema#23] opened 2017-05-16 11:38 UTC
Here is `make test` output
```
taransible@sh6:~/avro/tarantool-avro$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
taransible@sh6:~/avro/tarantool-avro$ make test
Running tests...
Test project /home/taransible/avro/tarantool-avro
    Start 1: ddt_tests
1/3 Test #1: ddt_tests ........................   Passed    0.24 sec
    Start 2: api_tests
2/3 Test #2: api_tests ........................   Passed    0.05 sec
    Start 3: buf_grow_test
3/3 Test #3: buf_grow_test ....................   Passed    0.06 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =   0.35 sec
taransible@sh6:~/avro/tarantool-avro$ make test
Running tests...
Test project /home/taransible/avro/tarantool-avro
    Start 1: ddt_tests
1/3 Test #1: ddt_tests ........................***Failed    0.26 sec
    Start 2: api_tests
2/3 Test #2: api_tests ........................   Passed    0.04 sec
    Start 3: buf_grow_test
3/3 Test #3: buf_grow_test ....................   Passed    0.04 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =   0.34 sec

The following tests FAILED:
	  1 - ddt_tests (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8
```

ddt tests chance of failure ~= 30%

Looks like floating bug

**Comment by Khatskevich** [comment] 2018-08-10 17:40
duplicate of #11

**Closed by Khatskevich** 2018-08-10 17:40 UTC
